org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Metadata
mod_id=energytoemc
mod_name=Energy To Emc
mod_version=1.0.0
mod_group_id=com.seccad_elizade.energytoemc
mod_authors=Seccad
mod_description=Converting Energy to EMC
mod_license=MIT

# Versions
minecraft_version=1.16.5
minecraft_version_range=[1.16.5]
forge_version=36.2.34
forge_version_range=[36.2,)
loader_version_range=[36,)