org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=energytoemc
mod_name=Energy To EMC
mod_license=MIT
mod_version=1.0.1
mod_authors=Seccad Elizade
mod_description=Converts Energy (FE) into EMC using ProjectE. Ported to Forge 1.16.5.

minecraft_version=1.16.5
minecraft_version_range=[1.16.5]
forge_version=36.2.34
forge_version_range=[36.2,)
loader_version_range=[36,)